### ISSUE TITLE
Comparison with gofmt/gofix

### ISSUE THREAD

**Issue by Deleplace** [xdg-go/go-rewrap-errors#3]
Hi David
I like the idea of working at the AST level for mechanical source transformation, and using "go/ast" in go-rewrap-errors is extremely powerful and flexible.

I suspect most rules are simple enough to be applied directly using gofmt or gofix:
`gofmt -r 'errors.Wrap(err, x) -> fmt.Errorf(x+": %w", err)'`
`gofmt -r 'errors.Wrap(x, fmt.Sprintf(p, y)) -> fmt.Errorf(p+": %w", y, x)'`
etc.

This is not widely known/documented, so I wrote an article about it: [A sample of source transformation of Go code](https://medium.com/@val_deleplace/a-sample-of-source-transformation-of-go-code-c96a6ab2b47c)

Afaiu gofmt works at the AST level as well.
Do you have an opinion on this?

Thanks again for the nice tool & nice article

**Comment by xdg** [comment]
Sorry I missed this -- my GH notifications were accidentally mass-disabled a while ago.

The case I'd be concerned using `gofmt` for is this one that manipulates a quoted string:
```
errors.Wrap(err, fmt.Sprintf("text %s", s)) -> fmt.Errorf("text %s: %w", s, err)
```
But maybe `gofmt` is clever enough -- I haven't tried.

Thanks for writing an article yourself!  The more we share knowledge the more we help the next person with the problem.  :grin:

**Comment by Deleplace** [comment]
Thanks David for the late reply.
`gofmt` does seem "clever enough" with one caveat though: it wouldn't automagically fix the imports, so an extra `goimports` command seems appropriate.

```
$ cat sample.go 
package main

import (
	"fmt"
	"log"

	"github.com/pkg/errors"
)

func main() {
	task := "baz"
	err := heavyWork(task)
	if err != nil {
		err2 := errors.Wrap(err, fmt.Sprintf("text %s", task))
		log.Fatal(err2)
	}
	fmt.Println("OK")
}

func heavyWork(task string) error {
	return fmt.Errorf("foobar")
}

$ go run .
2021/12/21 15:43:45 text baz: foobar
exit status 1
```

```
$ gofmt -w -r 'errors.Wrap(err, fmt.Sprintf("text %s", s)) -> fmt.Errorf("text %s: %w", s, err)' .

$ cat sample.go 
package main

import (
	"fmt"
	"log"

	"github.com/pkg/errors"
)

func main() {
	task := "baz"
	err := heavyWork(task)
	if err != nil {
		err2 := fmt.Errorf("text %s: %w", task, err)
		log.Fatal(err2)
	}
	fmt.Println("OK")
}

func heavyWork(task string) error {
	return fmt.Errorf("foobar")
}

$ go run .
# xxx
./sample.go:7:2: imported and not used: "github.com/pkg/errors" 
```

```
$ goimports -w .

$ go run .
2021/12/21 15:49:50 text baz: foobar
exit status 1
```
